/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.warpsample.ui;
import com.shephertz.app42.gaming.multiplayer.client.WarpClient;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

/**
 *
 * @author DHRUV CHOPRA
 */
public class WarpSampleUI extends javax.swing.JFrame {

    private WarpClient theClient;
    private String localUsername;
    /**
     * Creates new form WarpSampleUI
     */
    public WarpSampleUI() {
        initComponents();
        // Please replace with the API and Secret key pair received while registering.
        WarpClient.initialize("", "","");
        WarpClient.setRecoveryAllowance(60);
        try {
            theClient = WarpClient.getInstance();
        } catch (Exception ex) {
            Logger.getLogger(WarpSampleUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        theClient.addConnectionRequestListener(new ConnectionListener(this));    
        theClient.addZoneRequestListener(new ZoneListener(this));
        theClient.addRoomRequestListener(new RoomListen(this));
        theClient.addNotificationListener(new NotificationListener(this));        
        theClient.addLobbyRequestListener(new LobbyListener(this)); 
    }

    public WarpClient getClient(){
        return this.theClient;
    }
    
    public void appendNotifyResult(String result){
        notifyTextArea.append("\n"+result); 
    }
    
     public void appendLeaveNotifyResult(String result){
        leaveTextArea.append("\n"+result); 
    }
    
     public void appendResponseResult(String result){
        responseTextArea.append("\n"+result); 
    }
     
    public void appendChatResult(String result){
        //chatOutputArea.append("\n"+result); 
    }
    
    public void appendErrorNotificationResult(String result){
       // errorOutputArea.append("\n"+result); 
    }
    
    public String getInputText(){
        return chatText.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createRoomButton = new javax.swing.JButton();
        joinRoomButton = new javax.swing.JButton();
        chatText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        notifyTextArea = new javax.swing.JTextArea();
        connectButton = new javax.swing.JButton();
        notificationLabel = new javax.swing.JLabel();
        roomIdText = new javax.swing.JTextField();
        roomNameText = new javax.swing.JTextField();
        userText = new javax.swing.JTextField();
        chatButton = new javax.swing.JButton();
        subRoomButton = new javax.swing.JButton();
        subLobbyButton = new javax.swing.JButton();
        leaveRoomButton = new javax.swing.JButton();
        GetUserInfoButton = new javax.swing.JButton();
        RoomInfoButton = new javax.swing.JButton();
        LobbyInfoButton = new javax.swing.JButton();
        joinLobbyButton = new javax.swing.JButton();
        diconnectButton = new javax.swing.JButton();
        leaveLobbyButton = new javax.swing.JButton();
        sendUpdateButton = new javax.swing.JButton();
        getAllRoomButton = new javax.swing.JButton();
        getOnlineUsersButton = new javax.swing.JButton();
        setCustomUserDataButton = new javax.swing.JButton();
        userDataText = new javax.swing.JTextField();
        customRoomDataText = new javax.swing.JTextField();
        setCustomRoomDataText = new javax.swing.JButton();
        userDataText1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        responseTextArea = new javax.swing.JTextArea();
        notificationLabel1 = new javax.swing.JLabel();
        txtProperyName_1 = new javax.swing.JTextField();
        txtProperyValue = new javax.swing.JTextField();
        btnUnsubscribe = new javax.swing.JButton();
        btnUpdateProperty = new javax.swing.JButton();
        btnLockProperty = new javax.swing.JButton();
        btnUnlockProperty = new javax.swing.JButton();
        txtRemovePropery = new javax.swing.JTextField();
        txtProperyName = new javax.swing.JTextField();
        txtProperyValue_1 = new javax.swing.JTextField();
        txtMaxuser = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        leaveTextArea = new javax.swing.JTextArea();
        notificationLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createRoomButton.setText("createRoom");
        createRoomButton.setName("btnCreateRoom"); // NOI18N
        createRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRoomButtonActionPerformed(evt);
            }
        });

        joinRoomButton.setText("joinRoom");
        joinRoomButton.setName("btnJoinRoom"); // NOI18N
        joinRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinRoomButtonActionPerformed(evt);
            }
        });

        chatText.setText("message");
        chatText.setName("txtMessage"); // NOI18N
        chatText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatTextActionPerformed(evt);
            }
        });

        notifyTextArea.setColumns(20);
        notifyTextArea.setRows(5);
        jScrollPane1.setViewportView(notifyTextArea);

        connectButton.setText("Connect");
        connectButton.setName("btnConnect"); // NOI18N
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        notificationLabel.setText("Notifications");

        roomIdText.setText("room id");
        roomIdText.setName("txtRoomId"); // NOI18N

        roomNameText.setText("roomname");
        roomNameText.setName("txtCreateRoom"); // NOI18N

        userText.setText("username");
        userText.setName("txt"); // NOI18N
        userText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextActionPerformed(evt);
            }
        });

        chatButton.setText("send chat");
        chatButton.setName("btnSendChat"); // NOI18N
        chatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatButtonActionPerformed(evt);
            }
        });

        subRoomButton.setText("subscribeRoom");
        subRoomButton.setName("btnSubscribeRoom"); // NOI18N
        subRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subRoomButtonActionPerformed(evt);
            }
        });

        subLobbyButton.setText("Sub Lobby");
        subLobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subLobbyButtonActionPerformed(evt);
            }
        });

        leaveRoomButton.setText("leaveRoom");
        leaveRoomButton.setName("btnLeaveRoom"); // NOI18N
        leaveRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveRoomButtonActionPerformed(evt);
            }
        });

        GetUserInfoButton.setText("GetUserInfo");
        GetUserInfoButton.setName("btnGetUserInfo"); // NOI18N
        GetUserInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetUserInfoButtonActionPerformed(evt);
            }
        });

        RoomInfoButton.setText("GetRoomInfo");
        RoomInfoButton.setName("btnRoomInfo"); // NOI18N
        RoomInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomInfoButtonActionPerformed(evt);
            }
        });

        LobbyInfoButton.setText("GetLobbyInfo");
        LobbyInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LobbyInfoButtonActionPerformed(evt);
            }
        });

        joinLobbyButton.setText("JoinLobby");
        joinLobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinLobbyButtonActionPerformed(evt);
            }
        });

        diconnectButton.setText("Disconnect");
        diconnectButton.setName("btnDisconnect"); // NOI18N
        diconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diconnectButtonActionPerformed(evt);
            }
        });

        leaveLobbyButton.setText("LeaveLobby");
        leaveLobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveLobbyButtonActionPerformed(evt);
            }
        });

        sendUpdateButton.setText("send Update");
        sendUpdateButton.setName("btnSendUpdate"); // NOI18N
        sendUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendUpdateButtonActionPerformed(evt);
            }
        });

        getAllRoomButton.setText("Get All Room");
        getAllRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAllRoomButtonActionPerformed(evt);
            }
        });

        getOnlineUsersButton.setText("Get Online Users");
        getOnlineUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getOnlineUsersButtonActionPerformed(evt);
            }
        });

        setCustomUserDataButton.setText("Set custom User data");
        setCustomUserDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCustomUserDataButtonActionPerformed(evt);
            }
        });

        userDataText.setText("User Data");
        userDataText.setName("txtCustomData"); // NOI18N
        userDataText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDataTextActionPerformed(evt);
            }
        });

        customRoomDataText.setText("Custom room Data");
        customRoomDataText.setName("txtCustomRoomData"); // NOI18N
        customRoomDataText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customRoomDataTextActionPerformed(evt);
            }
        });

        setCustomRoomDataText.setText("Set custom Room Data");
        setCustomRoomDataText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCustomRoomDataTextActionPerformed(evt);
            }
        });

        userDataText1.setText("count");
        userDataText1.setName("txtCount"); // NOI18N
        userDataText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDataText1ActionPerformed(evt);
            }
        });

        jButton1.setText("clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jButton2.setText("send private chat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendPrivateChatActionPerformed(evt);
            }
        });

        jButton3.setText("send private update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendPrivateUpdateActionPerformed(evt);
            }
        });

        responseTextArea.setColumns(20);
        responseTextArea.setRows(5);
        jScrollPane2.setViewportView(responseTextArea);

        notificationLabel1.setText("Leave Notification");

        txtProperyName_1.setText("Property Name");

        txtProperyValue.setText("Property Value");
        txtProperyValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProperyValueActionPerformed(evt);
            }
        });

        btnUnsubscribe.setText("Unsubscribe room");
        btnUnsubscribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnsubscribeActionPerformed(evt);
            }
        });

        btnUpdateProperty.setText("update property");
        btnUpdateProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePropertyActionPerformed(evt);
            }
        });

        btnLockProperty.setText("lock property");
        btnLockProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLockPropertyActionPerformed(evt);
            }
        });

        btnUnlockProperty.setText("unlock property");
        btnUnlockProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnlockPropertyActionPerformed(evt);
            }
        });

        txtRemovePropery.setText("remove property");

        txtProperyName.setText("Property Name");

        txtProperyValue_1.setText("Property Value");
        txtProperyValue_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProperyValue_1ActionPerformed(evt);
            }
        });

        txtMaxuser.setText("maxuser");

        leaveTextArea.setColumns(20);
        leaveTextArea.setRows(5);
        jScrollPane3.setViewportView(leaveTextArea);

        notificationLabel2.setText("Responses");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chatText)
                            .addComponent(txtProperyName, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtProperyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtRemovePropery, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateProperty))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(userDataText1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(roomIdText)
                                    .addComponent(subLobbyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(createRoomButton)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(joinRoomButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(RoomInfoButton)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(subRoomButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(leaveRoomButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnUnsubscribe, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(GetUserInfoButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(customRoomDataText, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(setCustomRoomDataText, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LobbyInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(joinLobbyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(leaveLobbyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(getOnlineUsersButton))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(connectButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(diconnectButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(getAllRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(roomNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMaxuser, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(190, 190, 190)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userDataText, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setCustomUserDataButton)))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notificationLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(txtProperyName_1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProperyValue_1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnLockProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(btnUnlockProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(notificationLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(notificationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diconnectButton)
                    .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userDataText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setCustomUserDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAllRoomButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(roomNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaxuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customRoomDataText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(setCustomRoomDataText)
                        .addComponent(GetUserInfoButton)
                        .addComponent(createRoomButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(joinRoomButton)
                        .addComponent(subRoomButton)
                        .addComponent(roomIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RoomInfoButton)
                        .addComponent(leaveRoomButton))
                    .addComponent(btnUnsubscribe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subLobbyButton)
                    .addComponent(joinLobbyButton)
                    .addComponent(LobbyInfoButton)
                    .addComponent(leaveLobbyButton)
                    .addComponent(getOnlineUsersButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendUpdateButton)
                    .addComponent(chatButton)
                    .addComponent(userDataText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProperyValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateProperty)
                    .addComponent(txtRemovePropery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProperyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLockProperty)
                            .addComponent(btnUnlockProperty)
                            .addComponent(txtProperyName_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProperyValue_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(notificationLabel)
                                .addComponent(notificationLabel2)
                                .addComponent(notificationLabel1))
                            .addComponent(jButton1))
                        .addGap(2, 2, 2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userDataText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDataText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userDataText1ActionPerformed

    private void setCustomRoomDataTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCustomRoomDataTextActionPerformed
        theClient.setCustomRoomData(customRoomDataText.getText(), roomIdText.getText());

    }//GEN-LAST:event_setCustomRoomDataTextActionPerformed

    private void customRoomDataTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customRoomDataTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customRoomDataTextActionPerformed

    private void userDataTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDataTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userDataTextActionPerformed

    private void setCustomUserDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCustomUserDataButtonActionPerformed
        theClient.setCustomUserData(localUsername, userDataText.getText());
    }//GEN-LAST:event_setCustomUserDataButtonActionPerformed

    private void getOnlineUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getOnlineUsersButtonActionPerformed
        theClient.getOnlineUsers();
    }//GEN-LAST:event_getOnlineUsersButtonActionPerformed

    private void getAllRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllRoomButtonActionPerformed
        theClient.getAllRooms();
    }//GEN-LAST:event_getAllRoomButtonActionPerformed

    private void sendUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendUpdateButtonActionPerformed
       int i=0;
       int count=Integer.parseInt(userDataText1.getText());
       String message=chatText.getText();
       //notifyTextArea.append("\n count "+count+"message "+message);
       for(i=0;i<count;i++)
        {
             theClient.sendUpdatePeers(message.getBytes());
        }
    }//GEN-LAST:event_sendUpdateButtonActionPerformed

    private void leaveLobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveLobbyButtonActionPerformed
        theClient.leaveLobby();
    }//GEN-LAST:event_leaveLobbyButtonActionPerformed

    private void diconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diconnectButtonActionPerformed
        theClient.disconnect();
    }//GEN-LAST:event_diconnectButtonActionPerformed

    private void joinLobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinLobbyButtonActionPerformed
        theClient.joinLobby();
    }//GEN-LAST:event_joinLobbyButtonActionPerformed

    private void LobbyInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LobbyInfoButtonActionPerformed
        theClient.getLiveLobbyInfo();
    }//GEN-LAST:event_LobbyInfoButtonActionPerformed

    private void RoomInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomInfoButtonActionPerformed
        theClient.getLiveRoomInfo(roomIdText.getText());
    }//GEN-LAST:event_RoomInfoButtonActionPerformed

    private void GetUserInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetUserInfoButtonActionPerformed
        theClient.getLiveUserInfo(userText.getText());
    }//GEN-LAST:event_GetUserInfoButtonActionPerformed

    private void leaveRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveRoomButtonActionPerformed
        theClient.leaveRoom(roomIdText.getText());
    }//GEN-LAST:event_leaveRoomButtonActionPerformed

    private void subLobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subLobbyButtonActionPerformed
        theClient.subscribeLobby();
    }//GEN-LAST:event_subLobbyButtonActionPerformed

    private void subRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subRoomButtonActionPerformed
        theClient.subscribeRoom(roomIdText.getText());
    }//GEN-LAST:event_subRoomButtonActionPerformed

    private void chatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonActionPerformed
        int i=0;
        int count=Integer.parseInt(userDataText1.getText());
        String message=chatText.getText();
        //notifyTextArea.append("\n count "+count+"message "+message);
        for(i=0;i<count;i++)
        {
             theClient.sendChat(message);
        }
    }//GEN-LAST:event_chatButtonActionPerformed

    private void userTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        localUsername = userText.getText();
        theClient.connectWithUserName(localUsername);
    }//GEN-LAST:event_connectButtonActionPerformed

    private void chatTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chatTextActionPerformed

    private void joinRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinRoomButtonActionPerformed
        theClient.joinRoom(roomIdText.getText());
    }//GEN-LAST:event_joinRoomButtonActionPerformed

    private void createRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRoomButtonActionPerformed
        theClient.createRoom(roomNameText.getText(), localUsername,Integer.parseInt(txtMaxuser.getText()) ,null);
    }//GEN-LAST:event_createRoomButtonActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        notifyTextArea.setText("");
        responseTextArea.setText("");
        leaveTextArea.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSendPrivateChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendPrivateChatActionPerformed
       int i=0;
        int count=Integer.parseInt(userDataText1.getText());
        String message=chatText.getText();
        //notifyTextArea.append("\n count "+count+"message "+message);
        for(i=0;i<count;i++)
        {
             theClient.sendPrivateChat(userText.getText(),message);
        }
    }//GEN-LAST:event_btnSendPrivateChatActionPerformed

    private void btnSendPrivateUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendPrivateUpdateActionPerformed
     int i=0;
        int count=Integer.parseInt(userDataText1.getText());
        String message=chatText.getText();
        //notifyTextArea.append("\n count "+count+"message "+message);
    
        for(i=0;i<count;i++)
        {
             theClient.sendPrivateUpdate(userText.getText(),message.getBytes());
        }
    }//GEN-LAST:event_btnSendPrivateUpdateActionPerformed

    private void btnUnsubscribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnsubscribeActionPerformed
        // TODO add your handling code here:
        theClient.unsubscribeRoom(roomIdText.getText());
    }//GEN-LAST:event_btnUnsubscribeActionPerformed

    private void btnUpdatePropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePropertyActionPerformed
         HashMap<String, Object> tableProperties=new HashMap<String, Object>();
         if(!txtProperyName.getText().isEmpty())
         tableProperties.put(txtProperyName.getText(), txtProperyValue.getText());
         String[] str=new String[1];
         if(!txtRemovePropery.getText().isEmpty())    
             str[0]=txtRemovePropery.getText();
        theClient.updateRoomProperties(roomIdText.getText(), tableProperties, str);
    }//GEN-LAST:event_btnUpdatePropertyActionPerformed

    private void btnLockPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLockPropertyActionPerformed
        // TODO add your handling code here:
         HashMap<String, Object> tableProperties=new HashMap<String, Object>();
          if(!txtProperyName_1.getText().isEmpty())
         tableProperties.put(txtProperyName_1.getText(), txtProperyValue_1.getText());
        theClient.lockProperties(tableProperties);
    }//GEN-LAST:event_btnLockPropertyActionPerformed

    private void btnUnlockPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnlockPropertyActionPerformed
        // TODO add your handling code here:
         String[] str=new String[1];
         if(!txtProperyName_1.getText().isEmpty())    
             str[0]=txtProperyName_1.getText();
         theClient.unlockProperties(str);
    }//GEN-LAST:event_btnUnlockPropertyActionPerformed

    private void txtProperyValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProperyValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProperyValueActionPerformed

    private void txtProperyValue_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProperyValue_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProperyValue_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarpSampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarpSampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarpSampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarpSampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new WarpSampleUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetUserInfoButton;
    private javax.swing.JButton LobbyInfoButton;
    private javax.swing.JButton RoomInfoButton;
    private javax.swing.JButton btnLockProperty;
    private javax.swing.JButton btnUnlockProperty;
    private javax.swing.JButton btnUnsubscribe;
    private javax.swing.JButton btnUpdateProperty;
    private javax.swing.JButton chatButton;
    private javax.swing.JTextField chatText;
    private javax.swing.JButton connectButton;
    private javax.swing.JButton createRoomButton;
    private javax.swing.JTextField customRoomDataText;
    private javax.swing.JButton diconnectButton;
    private javax.swing.JButton getAllRoomButton;
    private javax.swing.JButton getOnlineUsersButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton joinLobbyButton;
    private javax.swing.JButton joinRoomButton;
    private javax.swing.JButton leaveLobbyButton;
    private javax.swing.JButton leaveRoomButton;
    private javax.swing.JTextArea leaveTextArea;
    private javax.swing.JLabel notificationLabel;
    private javax.swing.JLabel notificationLabel1;
    private javax.swing.JLabel notificationLabel2;
    private javax.swing.JTextArea notifyTextArea;
    private javax.swing.JTextArea responseTextArea;
    private javax.swing.JTextField roomIdText;
    private javax.swing.JTextField roomNameText;
    private javax.swing.JButton sendUpdateButton;
    private javax.swing.JButton setCustomRoomDataText;
    private javax.swing.JButton setCustomUserDataButton;
    private javax.swing.JButton subLobbyButton;
    private javax.swing.JButton subRoomButton;
    private javax.swing.JTextField txtMaxuser;
    private javax.swing.JTextField txtProperyName;
    private javax.swing.JTextField txtProperyName_1;
    private javax.swing.JTextField txtProperyValue;
    private javax.swing.JTextField txtProperyValue_1;
    private javax.swing.JTextField txtRemovePropery;
    private javax.swing.JTextField userDataText;
    private javax.swing.JTextField userDataText1;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
