/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.warpsample.ui;
import com.shephertz.app42.gaming.multiplayer.client.WarpClient;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

/**
 *
 * @author DHRUV CHOPRA
 */
public class WarpSampleUI extends javax.swing.JFrame {

    private WarpClient theClient;
    private String localUsername;
    /**
     * Creates new form WarpSampleUI
     */
    public WarpSampleUI() {
        initComponents();
        
        // Please replace with the API and Secret key pair received while registering.
        WarpClient.initialize("", "");
        
        try {
            theClient = WarpClient.getInstance();
        } catch (Exception ex) {
            Logger.getLogger(WarpSampleUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        theClient.addConnectionRequestListener(new ConnectionListener(this));    
        theClient.addZoneRequestListener(new ZoneListener(this));
        theClient.addRoomRequestListener(new RoomListen(this));
        theClient.addNotificationListener(new NotificationListener(this));        
        theClient.addLobbyRequestListener(new LobbyListener(this));
                
    }

    public WarpClient getClient(){
        return this.theClient;
    }
    
    public void appendResult(String result){
        outPutArea.append("\n"+result); 
    }
    public void appendChatResult(String result){
        chatOutputArea.append("\n"+result); 
    }
    
    public void appendErrorNotificationResult(String result){
        errorOutputArea.append("\n"+result); 
    }
    
    public String getInputText(){
        return chatText.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        authButton = new javax.swing.JButton();
        createRoomButton = new javax.swing.JButton();
        joinRoomButton = new javax.swing.JButton();
        chatText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outPutArea = new javax.swing.JTextArea();
        connectButton = new javax.swing.JButton();
        notificationLabel = new javax.swing.JLabel();
        roomIdText = new javax.swing.JTextField();
        roomNameText = new javax.swing.JTextField();
        userText = new javax.swing.JTextField();
        chatButton = new javax.swing.JButton();
        subRoomButton = new javax.swing.JButton();
        subLobbyButton = new javax.swing.JButton();
        leaveRoomButton = new javax.swing.JButton();
        GetUserInfoButton = new javax.swing.JButton();
        RoomInfoButton = new javax.swing.JButton();
        LobbyInfoButton = new javax.swing.JButton();
        joinLobbyButton = new javax.swing.JButton();
        diconnectButton = new javax.swing.JButton();
        leaveLobbyButton = new javax.swing.JButton();
        sendUpdateButton = new javax.swing.JButton();
        getAllRoomButton = new javax.swing.JButton();
        getOnlineUsersButton = new javax.swing.JButton();
        setCustomUserDataButton = new javax.swing.JButton();
        userDataText = new javax.swing.JTextField();
        chatNotificationLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatOutputArea = new javax.swing.JTextArea();
        customRoomDataText = new javax.swing.JTextField();
        setCustomRoomDataText = new javax.swing.JButton();
        errorNotificationLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        errorOutputArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        authButton.setText("authenticate");
        authButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authButtonActionPerformed(evt);
            }
        });

        createRoomButton.setText("createRoom");
        createRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRoomButtonActionPerformed(evt);
            }
        });

        joinRoomButton.setText("joinRoom");
        joinRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinRoomButtonActionPerformed(evt);
            }
        });

        chatText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatTextActionPerformed(evt);
            }
        });

        outPutArea.setColumns(20);
        outPutArea.setRows(5);
        jScrollPane1.setViewportView(outPutArea);

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        notificationLabel.setText("Notifications");

        roomIdText.setText("room id");

        roomNameText.setText("roomname");

        userText.setText("username");
        userText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextActionPerformed(evt);
            }
        });

        chatButton.setText("send chat");
        chatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatButtonActionPerformed(evt);
            }
        });

        subRoomButton.setText("subscribeRoom");
        subRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subRoomButtonActionPerformed(evt);
            }
        });

        subLobbyButton.setText("Sub Lobby");
        subLobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subLobbyButtonActionPerformed(evt);
            }
        });

        leaveRoomButton.setText("leaveRoom");
        leaveRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveRoomButtonActionPerformed(evt);
            }
        });

        GetUserInfoButton.setText("GetUserInfo");
        GetUserInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetUserInfoButtonActionPerformed(evt);
            }
        });

        RoomInfoButton.setText("GetRoomInfo");
        RoomInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomInfoButtonActionPerformed(evt);
            }
        });

        LobbyInfoButton.setText("GetLobbyInfo");
        LobbyInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LobbyInfoButtonActionPerformed(evt);
            }
        });

        joinLobbyButton.setText("JoinLobby");
        joinLobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinLobbyButtonActionPerformed(evt);
            }
        });

        diconnectButton.setText("Disconnect");
        diconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diconnectButtonActionPerformed(evt);
            }
        });

        leaveLobbyButton.setText("LeaveLobby");
        leaveLobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveLobbyButtonActionPerformed(evt);
            }
        });

        sendUpdateButton.setText("send Update");
        sendUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendUpdateButtonActionPerformed(evt);
            }
        });

        getAllRoomButton.setText("Get All Room");
        getAllRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAllRoomButtonActionPerformed(evt);
            }
        });

        getOnlineUsersButton.setText("Get Online Users");
        getOnlineUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getOnlineUsersButtonActionPerformed(evt);
            }
        });

        setCustomUserDataButton.setText("Set custom User data");
        setCustomUserDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCustomUserDataButtonActionPerformed(evt);
            }
        });

        userDataText.setText("User Data");
        userDataText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDataTextActionPerformed(evt);
            }
        });

        chatNotificationLabel.setText("Chat Notifications");

        chatOutputArea.setColumns(20);
        chatOutputArea.setRows(5);
        jScrollPane2.setViewportView(chatOutputArea);

        customRoomDataText.setText("Custom room Data");
        customRoomDataText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customRoomDataTextActionPerformed(evt);
            }
        });

        setCustomRoomDataText.setText("Set custom Room Data");
        setCustomRoomDataText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCustomRoomDataTextActionPerformed(evt);
            }
        });

        errorNotificationLabel.setText("Error Notifications");

        errorOutputArea.setColumns(20);
        errorOutputArea.setRows(5);
        jScrollPane3.setViewportView(errorOutputArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(customRoomDataText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(setCustomRoomDataText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(connectButton)
                                .addGap(88, 88, 88)
                                .addComponent(diconnectButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(authButton)
                                .addGap(18, 18, 18)
                                .addComponent(GetUserInfoButton)
                                .addGap(18, 18, 18)
                                .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(subLobbyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LobbyInfoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(joinLobbyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(leaveLobbyButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sendUpdateButton)
                                .addGap(29, 29, 29)
                                .addComponent(chatButton)
                                .addGap(18, 18, 18)
                                .addComponent(chatText, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(createRoomButton)
                                .addGap(18, 18, 18)
                                .addComponent(roomNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(getAllRoomButton))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(getOnlineUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(userDataText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(setCustomUserDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(errorNotificationLabel))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(joinRoomButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(RoomInfoButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(subRoomButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(leaveRoomButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(roomIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(chatNotificationLabel)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(notificationLabel)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(notificationLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diconnectButton))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(authButton)
                                    .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GetUserInfoButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(joinRoomButton)
                                    .addComponent(subRoomButton)
                                    .addComponent(roomIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RoomInfoButton)
                                    .addComponent(leaveRoomButton))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(subLobbyButton)
                                    .addComponent(joinLobbyButton)
                                    .addComponent(LobbyInfoButton)
                                    .addComponent(leaveLobbyButton))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(createRoomButton)
                                    .addComponent(roomNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(getAllRoomButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chatButton)
                                    .addComponent(chatText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sendUpdateButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(getOnlineUsersButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chatNotificationLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(userDataText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(setCustomUserDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(errorNotificationLabel)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(customRoomDataText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(setCustomRoomDataText))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chatTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chatTextActionPerformed

    private void authButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authButtonActionPerformed
        localUsername = userText.getText();
        theClient.joinZone(localUsername);
    }//GEN-LAST:event_authButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        theClient.connect();
    }//GEN-LAST:event_connectButtonActionPerformed

    private void createRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRoomButtonActionPerformed
        theClient.createRoom(roomNameText.getText(), localUsername, 5);
    }//GEN-LAST:event_createRoomButtonActionPerformed

    private void joinRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinRoomButtonActionPerformed
        theClient.joinRoom(roomIdText.getText());
    }//GEN-LAST:event_joinRoomButtonActionPerformed

    private void subRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subRoomButtonActionPerformed
        theClient.subscribeRoom(roomIdText.getText());
    }//GEN-LAST:event_subRoomButtonActionPerformed

    private void subLobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subLobbyButtonActionPerformed
        theClient.subscribeLobby();
    }//GEN-LAST:event_subLobbyButtonActionPerformed

    private void chatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonActionPerformed
        theClient.sendChat(chatText.getText());
    }//GEN-LAST:event_chatButtonActionPerformed

    private void leaveRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveRoomButtonActionPerformed
        theClient.leaveRoom(roomIdText.getText());
    }//GEN-LAST:event_leaveRoomButtonActionPerformed

    private void GetUserInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetUserInfoButtonActionPerformed
        theClient.getLiveUserInfo(userText.getText());
    }//GEN-LAST:event_GetUserInfoButtonActionPerformed

    private void userTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextActionPerformed

    private void leaveLobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveLobbyButtonActionPerformed
        theClient.leaveLobby();
    }//GEN-LAST:event_leaveLobbyButtonActionPerformed

    private void diconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diconnectButtonActionPerformed
        theClient.disconnect();
    }//GEN-LAST:event_diconnectButtonActionPerformed

    private void RoomInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomInfoButtonActionPerformed
        theClient.getLiveRoomInfo(roomIdText.getText());
    }//GEN-LAST:event_RoomInfoButtonActionPerformed

    private void LobbyInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LobbyInfoButtonActionPerformed
        theClient.getLiveLobbyInfo();
    }//GEN-LAST:event_LobbyInfoButtonActionPerformed

    private void joinLobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinLobbyButtonActionPerformed
        theClient.joinLobby();
    }//GEN-LAST:event_joinLobbyButtonActionPerformed

    private void sendUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendUpdateButtonActionPerformed
        theClient.sendUpdatePeers(chatText.getText().getBytes());
    }//GEN-LAST:event_sendUpdateButtonActionPerformed

    private void getAllRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllRoomButtonActionPerformed
        theClient.getAllRooms();
    }//GEN-LAST:event_getAllRoomButtonActionPerformed

    private void getOnlineUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getOnlineUsersButtonActionPerformed
        theClient.getOnlineUsers();
    }//GEN-LAST:event_getOnlineUsersButtonActionPerformed

    private void setCustomUserDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCustomUserDataButtonActionPerformed
       theClient.setCustomUserData(localUsername, userDataText.getText());
    }//GEN-LAST:event_setCustomUserDataButtonActionPerformed

    private void userDataTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDataTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userDataTextActionPerformed

    private void customRoomDataTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customRoomDataTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customRoomDataTextActionPerformed

    private void setCustomRoomDataTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCustomRoomDataTextActionPerformed
        theClient.setCustomRoomData(customRoomDataText.getText(), roomIdText.getText());
       
    }//GEN-LAST:event_setCustomRoomDataTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarpSampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarpSampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarpSampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarpSampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new WarpSampleUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetUserInfoButton;
    private javax.swing.JButton LobbyInfoButton;
    private javax.swing.JButton RoomInfoButton;
    private javax.swing.JButton authButton;
    private javax.swing.JButton chatButton;
    private javax.swing.JLabel chatNotificationLabel;
    private javax.swing.JTextArea chatOutputArea;
    private javax.swing.JTextField chatText;
    private javax.swing.JButton connectButton;
    private javax.swing.JButton createRoomButton;
    private javax.swing.JTextField customRoomDataText;
    private javax.swing.JButton diconnectButton;
    private javax.swing.JLabel errorNotificationLabel;
    private javax.swing.JTextArea errorOutputArea;
    private javax.swing.JButton getAllRoomButton;
    private javax.swing.JButton getOnlineUsersButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton joinLobbyButton;
    private javax.swing.JButton joinRoomButton;
    private javax.swing.JButton leaveLobbyButton;
    private javax.swing.JButton leaveRoomButton;
    private javax.swing.JLabel notificationLabel;
    private javax.swing.JTextArea outPutArea;
    private javax.swing.JTextField roomIdText;
    private javax.swing.JTextField roomNameText;
    private javax.swing.JButton sendUpdateButton;
    private javax.swing.JButton setCustomRoomDataText;
    private javax.swing.JButton setCustomUserDataButton;
    private javax.swing.JButton subLobbyButton;
    private javax.swing.JButton subRoomButton;
    private javax.swing.JTextField userDataText;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
